trainer:
  max_epochs: 20
  precision: "16-mixed"
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      resume: allow
      project: "eomt"
      name: "finetune_cityscapes_semantic_eomt_base_640"
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "metrics/val_iou_all" 
        mode: "max"        
        save_top_k: 1      
        save_last: true
        filename: "best"
model:
  class_path: eomt.training.mask_classification_semantic.MaskClassificationSemantic
  init_args:
    attn_mask_annealing_enabled: False
    network:
      class_path: eomt.models.eomt.EoMT
      init_args:
        num_q: 200 
        num_blocks: 3
        unfreeze_last_n_blocks: 0
        encoder:
          class_path: eomt.models.vit.ViT
          init_args:
            backbone_name: vit_base_patch14_reg4_dinov2
data:
  class_path: eomt.datasets.cityscapes_semantic.CityscapesSemantic
  init_args:
    img_size: [640, 640]